### ISSUE TITLE
Hard to make a limesurvey_ynh update of LS core

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/limesurvey_ynh#1]
From @Shnoulle

> Hi,
> 
> Actually limesurvey_ynh is a fork of github/limesurvey, but actually, i don't think it's realy a fork.
> 
> I want to fork t : i can only add it to LimeSurvey clone i have. It make hardest to update only LS core for example.
> 
> I think, but maybe it's a false good idea, it can be cleanest if:
> - limesurvey_ynh is a new project, include last build version of limesurvey for source
> - make it 'not updatable' in config (easy)
> - activate LDAP plugin and LDAP settings like you made it actually.
> - Make a new controller command inside LS to allow using updater (DB) from LS core (i can do it ;) ).
> - Update LS core is just : update sources + call this new controller.
> 
> I can start a new ls_ynh with your code if you'r OK, but i need to start from scatch and make copy/paste. I loose all GIT history ....
> 
> Denis

**Comment by zamentur** [comment]
> - limesurvey_ynh is a new project, include last build version of limesurvey for source

Yes, limesurvey_ynh should be a new project, I have had a bad idea to fork the repo... So I   recreated the repo...
Concerning update source code I am doing it now.

> - make it 'not updatable' in config (easy)

Easy but I don't understand  :/ .

> - activate LDAP plugin and LDAP settings like you made it actually.

OK.

> - Make a new controller command inside LS to allow using updater (DB) from LS core (i can do it ;) ).
> - Update LS core is just : update sources + call this new controller.

Feel free to create a system to upgrade this app...

I am currently working on to correct some problems with ldap. Users has to be in db to connect with their ldap password, so the install script need to be fixed...

**Comment by Shnoulle** [comment]
Yep, user in DB is a know issue on LS core (see https://github.com/LimeSurvey/LimeSurvey/pull/288 for example). But actually, we seperate authentification and Permission in develop version (ls3).

I think we can construct some "yunohost" specific plugin for SSO and LDAP. I have a look :)

**Comment by zamentur** [comment]
I have updated sources.
The problem with users who can't access is fixed too.
And I added an upgrade script.
I have move upload dir to /home/yunohost.app

Now there is the sso problem. I dont succeed to connect user with ssowat and the werserver authentication module, any idea ?

**Comment by Shnoulle** [comment]
I take a look , i know some LS core system ;)

PS : thanks a lot !!

**Comment by Shnoulle** [comment]
Can be closed :)

And next AuthLdap plugin allow user creation when needed (and can easily be forked)
