### ISSUE TITLE
Failed for Corrupt source

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/limesurvey_ynh#27]
Limesurvey échoue à l'installation en raison d'une erreur avec la somme de contrôle !

`Warning: yunohost.hook <lambda> - [746.1] Corrupt source`

**Comment by maniackcrudelis** [comment]
@zamentur 

Ce n'est donc pas la somme de contrôle mais le lien qui ne fonctionne plus.
Je pense qu'utiliser les releases github serait plus stable
https://github.com/LimeSurvey/LimeSurvey/releases/tag/2.62.2%2B170203

Je fais une PR en conséquence.
En l'état l'application ne peut pas être installée.

**Comment by zamentur** [comment]
Ce bug n'est plus d'actualité merci aux contributeurs
