### ISSUE TITLE
update

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/limesurvey_ynh#3]
Please update to 2.06

**Comment by Shnoulle** [comment]
Propose update to 2.6.2 lts + other fix : https://github.com/Shnoulle/LimeSurvey-Shnoulle/blob/2.06_SondagesPro/CHANGELOG.md 

I take it if OK

**Comment by zamentur** [comment]
Have you progressed ?
I am working on it too

**Comment by Shnoulle** [comment]
Not a lot : i do some UpdateController in LimeSurvey command directly. ANd do some test of updating. But don't work a lot on ynh part.

See 

- https://github.com/YunoHost-Apps/limesurvey_ynh/issues/8
- https://github.com/YunoHost-Apps/limesurvey_ynh/issues/7

too, it's more question for user's.

**Comment by Shnoulle** [comment]
For updating (after update)
- https://framagit.org/Shnoulle/LimeSurvey/commit/7ca49326dafe4d9896e67aebe414edcd3ce8c1af
- https://github.com/SondagesPro/LimeSurvey-SondagesPro/commit/7ca49326dafe4d9896e67aebe414edcd3ce8c1af

**Comment by zamentur** [comment]
I think it's done
