### ISSUE TITLE
E: Unable to locate package limesurvey-ynh-deps

### ISSUE THREAD

**Issue by ezekiel-lemur** [YunoHost-Apps/limesurvey_ynh#30]
I get this error when I try to install it on a root domain or a /page..

**Comment by zamentur** [comment]
I am not able to reproduce it, have you more context info to give me ?

**Comment by ramakirankumar** [comment]
Hi, Even i got the same error.
Click on Install, give the github url and click Install.
In next steps, change the name from "LimeSurvey" to "Survey" and change the path from "/poll" to "/survey", remove public checkbox and proceed.
I have 2 domains in my solution and iam trying to deploy on the default domain itself. Below is the log for reference.
[yunohost_limesurveylog.txt](https://github.com/YunoHost-Apps/limesurvey_ynh/files/1708667/yunohost_limesurveylog.txt)
