### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by schaengel** [YunoHost-Apps/limesurvey_ynh#31]
I am unable to install it on older and latest yunohost.

Current version: `2.6.4`

Main issue was `UnicodeDecodeError: 'ascii' codec can't decode byte`

The trace is given below.
 >'yunohost app checkurl' is deprecated and will be removed in the future
Warning: Traceback (most recent call last):
Warning:   File "<string>", line 1, in <module>
Warning:   File "/usr/lib/python3.4/json/__init__.py", line 265, in load
Warning:     return loads(fp.read(),
Warning:   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
Warning:     return codecs.ascii_decode(input, self.errors)[0]
Warning: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 230: ordinal not in range(128)
Warning: Traceback (most recent call last):
Warning:   File "<string>", line 1, in <module>
Warning:   File "/usr/lib/python3.4/json/__init__.py", line 265, in load
Warning:     return loads(fp.read(),
Warning:   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
Warning:     return codecs.ascii_decode(input, self.errors)[0]
Warning: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 230: ordinal not in range(128)
Warning: 
Warning: Database limesurvey not found
Warning: The user limesurvey was not found
Warning: E: Unable to locate package limesurvey-ynh-deps

**Comment by zamentur** [comment]
Have you put special character in the input data for installation ? If yes on which question ?

**Comment by schaengel** [comment]
I only used `yunohost app install https://github.com/YunoHost-Apps/limesurvey_ynh`
