### ISSUE TITLE
Erreur à l'installation avec l'interface web

### ISSUE THREAD

**Issue by michelwend** [YunoHost-Apps/limesurvey_ynh#32]
Bonjour,
L'installation ne fonctionne pas avec yunohost 2.6.5 le message d'erreur est le suivant:
L'application est incompatible avec votre version de YunoHost : Le paquet de l'application doit être mis à jour pour suivre les changements de YunoHost.
Je vais donc attendre une mise à jour.

**Comment by frju365** [comment]
Peux-tu faire un `yunohost -v` en tant que root ? (moi j'ai réussi à l'installer alors que j'ai la même version que toi apparemment) Et pourrais-tu retenter d'installer l'application ?

**Comment by michelwend** [comment]
Voilà le retour de la commande:

> root@ns:~# yunohost -v
> yunohost: 2.6.5
> yunohost-admin: 2.6.2
> moulinette: 2.6.1
> ssowat: 2.6.8
> root@ns:~# 


Je viens de tenter une installation en ligne de commande et voici le retour:

> Attention : « yunohost app checkurl » est déprécié et sera bientôt supprimé
> Attention : ERROR 1007 (HY000) at line 1: Can't create database 'limesurvey'; database exists
> Attention :
> Attention : The user limesurvey was not found
> Succès ! La configuration de SSOwat a été générée
> Erreur : Échec de l'installation

Voilà pour le retour. Mais je vois ce matin que la version 2.7 de yunohost pointe le bout de son nez, peut-être que cela va résoudre le souci. En attendant merci pour votre réactivité

**Comment by frju365** [comment]
en fait, dans ton installation, pour que ça fonctionne il faut juste que tu supprimes la base de donnée mysql "limesurvey". Passer à une version plus récente de yunohost ne changera rien malheureusement.

**Comment by zamentur** [comment]
Concernant ce bug c'est parce que la version qui est déployée par le dépôt d'application communautaire est trop vielle. Je vais regarder pour proposer un changement à ce sujet.

**Comment by schaengel** [comment]
Faced the same issue with #31
