### ISSUE TITLE
How do you enable LDAP?

### ISSUE THREAD

**Issue by Mrs-Feathers** [YunoHost-Apps/limesurvey_ynh#44]
Hello! very nice port of limesurvey. only been able to see one issue.. but its a rather large one. when installing, only the user who installed it can log into it. so, i installed it on yunohost with user1... then it works and all. but then user2 comes on and it shows this 
<img width="902" alt="Screen Shot 2019-05-10 at 21 12 44" src="https://user-images.githubusercontent.com/1746550/57563186-d773e300-7368-11e9-9d45-a1e727cf1f5b.png">

and.. well, no other users other than the first one are able to login. LDAP plugin seems to be disabled by default, but enabling it doesn't seem to do anything. i'm still not able to login with any other users so LDAP doesn't seem to be working.

**Comment by Mrs-Feathers** [comment]
EDIT: i have clicked "allow everyone" in the application settings in the yunohost administration panel. that seems to have at least let everyone see the error instead of the yunohost login screen.

**Comment by zamentur** [comment]
COuld you try with the new testing version ?

Are you connected on yunohost when you connect on limesurvey ?
Have you selected "LDAP" when you log in ?

**Comment by Mrs-Feathers** [comment]
i'll update to the new version now.

i sign into yunohost and visit the admin page and that signs me in directly. i never see the limesurvey login page... but when i login, i enabled the LDAP plugin [seems to be disabled by default] but no change. only i can login [via yunohost] no other yunohost users can login [theres no login screen. it only tells them that this page is off limits.. so i assume LDAP might work fine, but maybe theres another issue? because i need my other staff members to be able to login via yunohost. not making limesurvey accounts... even if they view the front part, it still doesnt make the limesurvey account from their LDAP account.. so i dont know what to do. i'm the only one able to login when i'm just a task manager.. my human resources staff are supposed to be the ones with accounts to be logged in]

**Comment by Mrs-Feathers** [comment]
the update seems to have broken it. it used to be that i was automatically logged in.. now after reinstalling it presents me with a login. as you know, ldap is NOT enabled by default.. so now i'm just completely unable to login at all. theres no register button and no LDAP drop down. so now i myself cant even login.
<img width="490" alt="Screen Shot 2019-05-21 at 00 26 24" src="https://user-images.githubusercontent.com/1746550/58068369-18d17300-7b5f-11e9-9b0f-6bfb179871b5.png">

**Comment by dsmrs** [comment]
You can click on "forgot your password", ask for a new one, and then you will be able to enter in the admin panel. But it's definitly not like it should be.

**Comment by yalh76** [comment]
ldap is now enabled
