### ISSUE TITLE
Login fails due to too many redirects

### ISSUE THREAD

**Issue by hal3003** [YunoHost-Apps/limesurvey_ynh#55]
Hello,

I recently added a new user via the LDAP backend to my LimeSurvey instance, but can't login. If I login via SSO and the open the LimeSurvey admin panel, I get a browser error about too many redirects. This is quite strange, as I am currently logged in with another account. I'm also unsure about how to go about debugging this issue.

**Comment by tutle** [comment]
Hello
Since last update, I can't login to admin interface and had this error message too, any way to reset the admin interface ?
