### ISSUE TITLE
Question avant pull request

### ISSUE THREAD

**Issue by Shnoulle** [YunoHost-Apps/limesurvey_ynh#6]
Bonjour, 

Comme déjà indiqué je compte reprendre et sans doute maintenir limesurvey_ynh si vous êtes daccord (et après avoir fait mes preuves). Cependant, j'hésite ....

Il ya 2 version en // de limesurvey  

1. La branche 2.5/2.6 : celle de limesurvey_ynh : intéressantes, mais oldy en terme de look, peu de bug, une sorte de lts
2. La branche 2.5X : changement complet de look , existe depuis ~ 1an mais les précédents utilisateurs de LimeSurvey sont resté sur la branche 2.5/2.6. rencontre des bugs sur le coté public plus difficile à gérer que sur la 2.6

Il y a en plus : la branche 3.0 qui devrait sortir en alpha en janvier/février.

J'aurais tendance à passer sur une 2.6lts pour les mises à jours, éventuellement en modifiant le modèle par défaut (utilisation de SkeletonQuest plutot que le vieux modèle). Qu'en pensez vous ?

**Comment by zamentur** [comment]
De toute façon j'ai toujours trouvé que les thèmes LimeSurvey étaient pas jolie... 

Pour le choix entre SkeletonQuest et le vieux modèle je ne sais pas trop. En fait il y a des utilisateurs qui vont préférer l'un ou l'autre. Peut être devrait on poser la question lors de l'installation ?

**Comment by zamentur** [comment]
N'hésites pas à reprendre cette app, pour ma part je préfère actuellement me concentrer sur d'autres parties de YunoHost

**Comment by Shnoulle** [comment]
Salut,

C'est en cours pour la reprise , j'ai déjà corrigé une partie pour pouvoir faire la mise à jour par PHP cli. Il faut que je vérifie le passage de mise à jour sur l'autentification LDAP.

Pour les modèles 'par défaut', je regarde, au cas ou je laisse tel quel.
