### ISSUE TITLE
Usage of upload directory ?

### ISSUE THREAD

**Issue by Shnoulle** [YunoHost-Apps/limesurvey_ynh#7]
In install (and update) i see [$upload_path](https://github.com/YunoHost-Apps/limesurvey_ynh/blob/master/scripts/install#L56) : what is the usage ?

In fact LimeSurvey have some way to manage upload directory (and url) at different place .

It's to allow multiple install with only one sources files ? 
If yes : can we read different config files for each installation ? 

If yes : did it work currently or i can lost this dir during update ?

**Comment by zamentur** [comment]
For the moment I removed it. But the idea was to put data in /home/yunohost.app directory.
In some case, this data file could be very big... May be we need to adapat backup/restore.

**Comment by Shnoulle** [comment]
OK, then it can be set in config (for the directory : it's easy), but need to add it too in url (then ngynx update).

**Comment by Shnoulle** [comment]
Can this part can be usable for multiple install ?

I explain : for me a multi-install are : use same PHP but different DB and upload directory. It's the same for yunohost ?

If yes : the only are to use a different config.php file for each install , maybe load config according to HTTP_HOST  ? 

config.php in limesurvey directory

```
<?php 
include /etc/yunohost/apps/limesurvey/$_SERVER['SERVER_NAME']/config.php

```

$_SERVER['SERVER_NAME'] can surely replaced by a server var (for php-cli setting) , and maybe need a default.
