### ISSUE TITLE
Usage of Permission for Yunohost users

### ISSUE THREAD

**Issue by Shnoulle** [YunoHost-Apps/limesurvey_ynh#8]
New version add Auth Permission to allow (or not) a user to Authenticate via LDAP plugin or not.

Maybe this can be used to allow update user allowed to Authenticate ?
![capture du 2017-01-18 23-38-14](https://cloud.githubusercontent.com/assets/1439428/22086064/36ef8d90-ddd7-11e6-92a1-e4d9de1298b7.png)

This is OK for 'extra user' , but not for super admin user (the first created) : this one is always superadmin (user id == 1). 

Then it can not really use (or not) AuthLDAP : an idea for this ? 1st user can not be deleted from YunoHost admin ? Or create another super admin user ? Inform 1st user another super admin was created during installation, give him the root email ?

**Comment by zamentur** [comment]
LDAP and WebAuth is set up. 

About the admin user I don't know how to manage the admin password.

**Comment by Shnoulle** [comment]
If you think it's interesting : i can have a look where to add the instruction.

In fact : 
`php $local_path/application/commands/console.php resetpassword ADMINUSER ADMINPASSWORD` for any user (by name).

**Comment by zamentur** [comment]
May be i could generate a random password (the admin connect with his yunohost account via ldap/sso)

**Comment by Shnoulle** [comment]
Yes : the main question (from my POV) : yunohost offer different solutions and limesurvey too.

But the user with id 1 in limesurvey are the "super-super-admin" user : only this one can set other user to super-admin or remove super-admin rights.
Then if it's an Yunohost user : we can not really update it after installation

And more this super super admin user have always the right to access to LimeSurvey via DB (if the Auth was set to LDAP only : user have to forge POST value , but still possible to log in).

Some solution
- Super super admin user in LimeSurvey only
  - set user/password via php-cli
  - What password to set ? 
     1. random : user can not set/update if other user's are super-admin. Except if construct a way in yuunohost for this.
      2. choose : the person who set ls have all access and can create other user directly in LS
- Super super admin are an Yunohost account
  - yunohost account
  - Disable update of this 1st account in yunohost ?
  - If unable update : need a solution to update id in database 

And more : need all this part working when update .... Agin : if you need something in LS : ask me, i try to understand better the way of yunohost, ands when i'm ready i maintain this repo.

**Comment by zamentur** [comment]
> Then if it's an Yunohost user : we can not really update it after installation

I am not sure to understand why ?

Your problem is that the admin cannot be change ?

> Disable update of this 1st account in yunohost ?

Currently, it's not possible to change the username of a yunohost user

**Comment by Shnoulle** [comment]
Super-super-admin in Limesurvey : userid==1

I need to look at ls_ynh .... you create a super-super-admin only fro LS ?

**Comment by Shnoulle** [comment]
I close this one, think we can use a config settings for «forced admin» :)
